#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "action.h"


/* Read a binary file generated by bingen */
/* Into RAM or flash */

/* Variables */
menuitem_t menu[MAX_MENUITEMS];
uint8_t num_menuitems = 0;


void *bin_to_ram()
{
  FILE *fp_bin = fopen("example.bin", "rb");
  fseek(fp_bin, 0, SEEK_END);
  uint32_t size = ftell(fp_bin);
  rewind(fp_bin);

  void *ret = malloc(size);
  fread(ret, size, 1, fp_bin);

  fclose(fp_bin);
  return ret;
}

//uint32_t num_menuitems;
//uint32_t num_actions;
//db_menuitem_t *db_menuitems[32];

int main(void)
{
  uint32_t i, j;
  
  /* Get the database */
  void* db;
  db = bin_to_ram();
  void *curptr = db;

  memcpy(&num_menuitems, curptr, sizeof(uint32_t));
  curptr += sizeof(uint32_t);
  
  printf("%d menu items\n", num_menuitems);

  /* Read menuitems */
  for (i = 0; i < num_menuitems; i++)
  {
    /* Read a menuitem */
    db_menuitem_t *db_menuitem = (db_menuitem *) curptr;
    curptr += sizeof(db_menuitem_t);
    /* Debug */
    printf("Menuitem: icon=%ud, num_actions=%d\n",
           db_menuitem->icon_size, db_menuitem->num_actions);
           
    menu[i].num_actions = db_menuitem->num_actions;
    menu[i].icon_size = db_menuitem->icon_size;
  }
  printf("\n");

  for (i = 0; i < num_menuitems; i++)
  {
    printf("For menuitem %d\n", i);
    
    for (j = 0; j < db_menuitems[i]->num_actions; j++)
    {
      /* Read an action */
      db_action_t *action = curptr;
      curptr += sizeof(db_action_t);

      menu[i].actions[j] = curptr;

      printf("  Action: type=%d, pin=%d, val=%d, time=%d\n",
             action->type, action->pin, action->value, action->time);
    }
  }

  /* Read icons */
  for (i = 0; i < num_menuitems; i++)
  {
    menu[i].icon = (uint8_t *) curptr;
    curptr += db_menuitems[i]->icon_size;
  }


  return 0;
}
